kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-zookeeper-pv-claim
spec:
  storageClassName: azurefile-ensemble
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
