kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: store-zkensemble
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
  kind: Managed
  storageaccounttype: Premium_LRS
#  fsType: xfs
#  location: eastus
#  storageAccount: azure_storage_account_name
